//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.18 at 03:21:47 PM BRT 
//

package br.com.personalPrpject.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
/**
 * 
 * @author alersonr
 *
 */
public class EnderecoDozer {

	protected EnderecoDozer.Enderecos enderecos;

	/**
	 * Gets the value of the enderecos property.
	 * 
	 * @return possible object is {@link EnderecoDozer.Enderecos }
	 * 
	 */
	public EnderecoDozer.Enderecos getEnderecos() {
		return enderecos;
	}

	/**
	 * Sets the value of the enderecos property.
	 * 
	 * @param value
	 *            allowed object is {@link EnderecoDozer.Enderecos }
	 * 
	 */
	public void setEnderecos(EnderecoDozer.Enderecos value) {
		this.enderecos = value;
	}

	public static class Enderecos {

		protected List<EnderecoDozer.Enderecos.Endereco> endereco;

		public List<EnderecoDozer.Enderecos.Endereco> getEndereco() {
			if (endereco == null) {
				endereco = new ArrayList<EnderecoDozer.Enderecos.Endereco>();
			}
			return this.endereco;
		}

		public static class Endereco {

			@XmlElement(required = true)
			protected String cep;
			@XmlElement(required = true)
			protected String logradouro;
			@XmlElement(required = true)
			protected String complemento;
			@XmlElement(required = true)
			protected String bairro;
			@XmlElement(required = true)
			protected String localidade;
			@XmlElement(required = true)
			protected String uf;
			@XmlElement(required = true)
			protected String unidade;
			protected int ibge;
			@XmlElement(required = true)
			protected String gia;

			/**
			 * Gets the value of the cep property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCep() {
				return cep;
			}

			/**
			 * Sets the value of the cep property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCep(String value) {
				this.cep = value;
			}

			/**
			 * Gets the value of the logradouro property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLogradouro() {
				return logradouro;
			}

			/**
			 * Sets the value of the logradouro property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLogradouro(String value) {
				this.logradouro = value;
			}

			/**
			 * Gets the value of the complemento property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getComplemento() {
				return complemento;
			}

			/**
			 * Sets the value of the complemento property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setComplemento(String value) {
				this.complemento = value;
			}

			/**
			 * Gets the value of the bairro property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getBairro() {
				return bairro;
			}

			/**
			 * Sets the value of the bairro property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setBairro(String value) {
				this.bairro = value;
			}

			/**
			 * Gets the value of the localidade property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLocalidade() {
				return localidade;
			}

			/**
			 * Sets the value of the localidade property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLocalidade(String value) {
				this.localidade = value;
			}

			/**
			 * Gets the value of the uf property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getUf() {
				return uf;
			}

			/**
			 * Sets the value of the uf property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setUf(String value) {
				this.uf = value;
			}

			/**
			 * Gets the value of the unidade property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getUnidade() {
				return unidade;
			}

			/**
			 * Sets the value of the unidade property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setUnidade(String value) {
				this.unidade = value;
			}

			/**
			 * Gets the value of the ibge property.
			 * 
			 */
			public int getIbge() {
				return ibge;
			}

			/**
			 * Sets the value of the ibge property.
			 * 
			 */
			public void setIbge(int value) {
				this.ibge = value;
			}

			/**
			 * Gets the value of the gia property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getGia() {
				return gia;
			}

			/**
			 * Sets the value of the gia property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setGia(String value) {
				this.gia = value;
			}

		}

	}

}
