//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.18 at 03:21:47 PM BRT 
//


package br.com.personalPrpject.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Xmlcep }
     * 
     */
    public Xmlcep createXmlcep() {
        return new Xmlcep();
    }

    /**
     * Create an instance of {@link Xmlcep.Enderecos }
     * 
     */
    public Xmlcep.Enderecos createXmlcepEnderecos() {
        return new Xmlcep.Enderecos();
    }

    /**
     * Create an instance of {@link Xmlcep.Enderecos.Endereco }
     * 
     */
    public Xmlcep.Enderecos.Endereco createXmlcepEnderecosEndereco() {
        return new Xmlcep.Enderecos.Endereco();
    }

}
