//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.18 at 03:21:47 PM BRT 
//


package br.com.personalPrpject.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="enderecos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="endereco" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cep" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="logradouro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="complemento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="bairro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="localidade" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="uf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="unidade" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ibge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="gia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enderecos"
})
@XmlRootElement(name = "xmlcep")
public class Xmlcep {

    @XmlElement(required = true)
    protected Xmlcep.Enderecos enderecos;

    /**
     * Gets the value of the enderecos property.
     * 
     * @return
     *     possible object is
     *     {@link Xmlcep.Enderecos }
     *     
     */
    public Xmlcep.Enderecos getEnderecos() {
        return enderecos;
    }

    /**
     * Sets the value of the enderecos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xmlcep.Enderecos }
     *     
     */
    public void setEnderecos(Xmlcep.Enderecos value) {
        this.enderecos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="endereco" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cep" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="logradouro" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="complemento" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="bairro" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="localidade" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="uf" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="unidade" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ibge" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="gia" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "endereco"
    })
    public static class Enderecos {

        protected List<Xmlcep.Enderecos.Endereco> endereco;

        /**
         * Gets the value of the endereco property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the endereco property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEndereco().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Xmlcep.Enderecos.Endereco }
         * 
         * 
         */
        public List<Xmlcep.Enderecos.Endereco> getEndereco() {
            if (endereco == null) {
                endereco = new ArrayList<Xmlcep.Enderecos.Endereco>();
            }
            return this.endereco;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cep" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="logradouro" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="complemento" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="bairro" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="localidade" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="uf" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="unidade" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ibge" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="gia" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cep",
            "logradouro",
            "complemento",
            "bairro",
            "localidade",
            "uf",
            "unidade",
            "ibge",
            "gia"
        })
        public static class Endereco {

            @XmlElement(required = true)
            protected String cep;
            @XmlElement(required = true)
            protected String logradouro;
            @XmlElement(required = true)
            protected String complemento;
            @XmlElement(required = true)
            protected String bairro;
            @XmlElement(required = true)
            protected String localidade;
            @XmlElement(required = true)
            protected String uf;
            @XmlElement(required = true)
            protected String unidade;
            protected int ibge;
            @XmlElement(required = true)
            protected String gia;

            /**
             * Gets the value of the cep property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCep() {
                return cep;
            }

            /**
             * Sets the value of the cep property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCep(String value) {
                this.cep = value;
            }

            /**
             * Gets the value of the logradouro property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLogradouro() {
                return logradouro;
            }

            /**
             * Sets the value of the logradouro property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLogradouro(String value) {
                this.logradouro = value;
            }

            /**
             * Gets the value of the complemento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComplemento() {
                return complemento;
            }

            /**
             * Sets the value of the complemento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComplemento(String value) {
                this.complemento = value;
            }

            /**
             * Gets the value of the bairro property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBairro() {
                return bairro;
            }

            /**
             * Sets the value of the bairro property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBairro(String value) {
                this.bairro = value;
            }

            /**
             * Gets the value of the localidade property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalidade() {
                return localidade;
            }

            /**
             * Sets the value of the localidade property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalidade(String value) {
                this.localidade = value;
            }

            /**
             * Gets the value of the uf property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUf() {
                return uf;
            }

            /**
             * Sets the value of the uf property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUf(String value) {
                this.uf = value;
            }

            /**
             * Gets the value of the unidade property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnidade() {
                return unidade;
            }

            /**
             * Sets the value of the unidade property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnidade(String value) {
                this.unidade = value;
            }

            /**
             * Gets the value of the ibge property.
             * 
             */
            public int getIbge() {
                return ibge;
            }

            /**
             * Sets the value of the ibge property.
             * 
             */
            public void setIbge(int value) {
                this.ibge = value;
            }

            /**
             * Gets the value of the gia property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGia() {
                return gia;
            }

            /**
             * Sets the value of the gia property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGia(String value) {
                this.gia = value;
            }

        }

    }

}
